{
  "schema_version": "1.4.0",
  "id": "GHSA-82wx-rxf8-fxch",
  "modified": "2024-04-29T21:30:35Z",
  "published": "2024-04-29T21:30:35Z",
  "aliases": [
    "CVE-2023-46960"
  ],
  "details": "Buffer Overflow vulnerability in PyPXE v.1.8.4 allows a remote attacker to cause a denial of service via the handle function in the tftp module.",
  "severity": [

  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-46960"
    },
    {
      "type": "WEB",
      "url": "https://github.com/pypxe/PyPXE/issues/206"
    }
  ],
  "database_specific": {
    "cwe_ids": [

    ],
    "severity": null,
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2024-04-29T21:15:47Z"
  }
}